### PR TITLE
Ipo retgroup

### PR DESCRIPTION
**Pull request by lecorguille**
This update will bring the retcor fonction of IPO

### CODE REVIEW

**Comment by lecorguille** [comment]
1.  Dependencies merging issue
Though, I'm testing again the dev branch of Galayx, I have to use a "meta-package" to solve some ...
See: https://github.com/galaxyproject/galaxy/issues/3299#issuecomment-272202459

2. R-3.3.1: issue with cairo
Since, I get that
```
|  Error in .External2(C_X11, paste("jpeg::", quality, ":", filename, sep = ""),  :
|  unable to start device JPEG
|  Calls: ipo4xcmsSet ... optimizeXcmsSet -> xcmsSetStatistic -> plotContours -> jpeg
|  In addition: There were 22 warnings (use warnings() to see them)
|  Execution halted
```
Follow those links:
- https://github.com/bioconda/bioconda-recipes/issues/3270
- https://github.com/ContinuumIO/anaconda-issues/issues/1239
- https://github.com/conda-forge/staged-recipes/issues/2009

**Comment by lecorguille** [comment]
No more issue with jpeg (and no more "conda meta-package") since conda was update by Galaxy

**Comment by lecorguille** [comment]
ping @workflow4metabolomics/ms 

But but but, for retgroup I get this: https://travis-ci.org/workflow4metabolomics/ipo/builds/195920705#L2370

I using a xset generated with `MM8.mzML` and `MM14.mzML`  from the package `msdata`

The xcmsSet parameters:
```
nSlaves 1
method centWave
ppm 25
peakwidth 20 50
```

```
An "xcmsSet" object with 2 samples

Time range: 18.7-307.3 seconds (0.3-5.1 minutes)
Mass range: 117.0357-936.7059 m/z
Peaks: 255 (about 128 per sample)
Peak Groups: 0
Sample classes: .

Peak picking was performed on MS1.
Profile settings: method = bin
                  step = 0.1

Memory usage: 0.0321 MB
```
Any idea?

**Comment by jfrancoismartin** [comment]
Hi, I think that error occurs because the model is over fitting (warn.overcorrect <- TRUE). You should try with more samples. 
It is also difficult to assess minfrac parameter from 0.3 to 0.7 with only 2 samples. 30% of 2 samples is less than 1 samples. I recommend to set only 1 value to minfrac 0.5 or 1.
Good luck
JF

**Comment by lecorguille** [comment]
@jfrancoismartin 
It is better when I set `minfrac` on 1 but I still get error: https://travis-ci.org/workflow4metabolomics/ipo/builds/201902727#L2380

```
starting new DoE with:
bw: c(20.4, 39.6)
mzwid: c(0.013, 0.037)
span: c(0.08, 0.32)
minfrac: 1
retcorMethod: loess
smooth: loess
extra: 1
missing: 1
family: gaussian
plottype: none
minsamp: 1
max: 50
center: 2

Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
no increase stopping
```

I kept my test-data with the 2 samples. Are some phenoData mandatory?

**Comment by jfrancoismartin** [comment]
Ok, did you try the normal workflow (xcmsSet+group) with for example the minimum values of bw and mzwid (or average) ? Just to verify that there is something to find in those samples ?
It is bizarre that group coul'nt find any peak.
And I still think that using 4 samples for IPO would give better results...

**Comment by lecorguille** [comment]
@jfrancoismartin You are right! My input test-data seem not good.

- with `MM8.mzML` and `MM14.mzML` from `msdata`  
```
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
Error in .local(object, ...) : No group information found
```
Because I have no group even after `group`
```
method	density
sleep	0.001
minfrac	1
bw	22
mzwid	0.015
```
```
	XSET OBJECT INFO
An "xcmsSet" object with 2 samples

Time range: 18.7-307.3 seconds (0.3-5.1 minutes)
Mass range: 117.0357-936.7059 m/z
Peaks: 255 (about 128 per sample)
Peak Groups: 0 
Sample classes: . 

Peak picking was performed on MS1.
Profile settings: method = bin
                  step = 0.1
```
- with FaahKO
```xml
            <param name="group|methods|method" value="density"/>
            <param name="group|methods|bw" value="28,32"/>
            <param name="group|methods|minfrac" value="1"/>
            <param name="group|methods|mzwid" value="0.15,0.35"/>
            <param name="retcor|methods|method" value="peakgroups"/>
            <param name="retcor|methods|smooth" value="loess"/>
            <param name="retcor|methods|extra" value="1"/>
            <param name="retcor|methods|missing" value="1"/>
```
```
no increase stopping
There were 22 warnings (use warnings() to see them)
```
Also I get groups with `group`
```
method	density
sleep	0.001
minfrac	0.5
bw	30
mzwid	0.25
```
```
	XSET OBJECT INFO
An "xcmsSet" object with 4 samples

Time range: 2506.1-4477.9 seconds (41.8-74.6 minutes)
Mass range: 200.1-600 m/z
Peaks: 9251 (about 2313 per sample)
Peak Groups: 5740 
Sample classes: KO, WT 

Peak picking was performed on MS1.
Profile settings: method = bin
                  step = 0.1

Memory usage: 1.57 MB
```

**Comment by jfrancoismartin** [comment]
So ? did you try IPO with the four samples giving groups ?

**Comment by lecorguille** [comment]
Yes, I'm using the 4 samples. The same, I process with `group`

 - FaahKO
Here is my input:
```
An "xcmsSet" object with 4 samples

Time range: 2506.1-4477.9 seconds (41.8-74.6 minutes)
Mass range: 200.1-600 m/z
Peaks: 9251 (about 2313 per sample)
Peak Groups: 0
Sample classes: KO, WT

Profile settings: method = bin
                  step = 0.1

Memory usage: 0.862 MB
```

**Comment by lecorguille** [comment]
@jfrancoismartin 
I launch the process manually (it seems stupid to not have done that earlier)
I get those massage and warning
```
no increase stopping
There were 22 warnings (use warnings() to see them)
```
```
> warning()
Warning messages:
1: In .local(object, ...) : Span too small, resetting to 0.02
2: In .local(object, ...) : Span too small, resetting to 0.02
3: In .local(object, ...) : Span too small, resetting to 0.01
4: In .local(object, ...) : Span too small, resetting to 0.01
5: In .local(object, ...) : Span too small, resetting to 0.01
6: In .local(object, ...) : Span too small, resetting to 0.02
7: In .local(object, ...) : Span too small, resetting to 0.02
8: In .local(object, ...) : Span too small, resetting to 0.01
9: In .local(object, ...) : Span too small, resetting to 0.01
10: In .local(object, ...) : Span too small, resetting to 0.01
11: In .local(object, ...) : Span too small, resetting to 0.02
12: In .local(object, ...) : Span too small, resetting to 0.02
13: In .local(object, ...) : Span too small, resetting to 0.02
14: In .local(object, ...) : Span too small, resetting to 0.02
15: In .local(object, ...) :
  Fitted retention time deviation curves exceed points by more than 2x.
This is dangerous and the algorithm is probably overcorrecting your data.
Consider increasing the span parameter or switching to the linear smoothing method.
16: In .local(object, ...) : Span too small, resetting to 0.01
17: In .local(object, ...) : Span too small, resetting to 0.02
18: In .local(object, ...) : Span too small, resetting to 0.11
19: In .local(object, ...) : Span too small, resetting to 0.02
20: In .local(object, ...) : Span too small, resetting to 0.05
21: In .local(object, ...) : Span too small, resetting to 0.01
22: In .local(object, ...) : Span too small, resetting to 0.02
```

But eventually, I get some outputs :/
I was fucusing on those warning and because I tried to get the parameters with `resultRetcorGroup$best_settings$parameters` like for the xcms part of IPO, I miss them.

```
> resultRetcorGroup$best_settings
$bw
[1] 5.959782
$mzwid
[1] 1e-04
$span
[1] 0.05650336
$minfrac
[1] 1
$retcorMethod
[1] "loess"
$smooth
[1] "loess"
$extra
[1] 1
$missing
[1] 1
$family
[1] "gaussian"
$plottype
[1] "none"
$minsamp
[1] 1
$max
[1] 50
$center
[1] 2
```

It's pretty good :)

But still, can you explain me why I get a `bw` of `5.959782` while I have set a range of `28,32`?

**Comment by jfrancoismartin** [comment]
@lecorguille 
So it seems to work...  
Actually IPO use some design of experiment(response surface I think) and the parameter give initially are not a range of possible data. It is just a starting point for the algorithm (iterative) which can find a best value outside the range of initial values. This is the power of this kind of design. But this can disturb the users...

**Comment by lecorguille** [comment]
Good news
I will be able to finish a first round
But I will have to work on the form to limit the possibility and the process duration

**Comment by lecorguille** [comment]
GREEN!
Many thanks @jfrancoismartin

**Pull request merged**
